// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="StealFocus">
//   Copyright StealFocus. All rights reserved.
// </copyright>
// <summary>
//   GlobalSuppressions.cs
// </summary>
// --------------------------------------------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Does_Not_Exist()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_But_Not_On_A_Scheduled_Day()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_Not_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Does_Not_Exist()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_But_Not_On_A_Scheduled_Day()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_Not_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.TableDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.TableDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_But_Not_On_A_Scheduled_Day()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.TableDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_Not_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.BlobContainerDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.BlobContainerDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_Not_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.BlobContainerDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_But_Not_On_A_Scheduled_Day()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.TableDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Table_Does_Not_Exist()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.StorageService.BlobContainerDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Blob_Does_Not_Exist()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Check_Exists_Throws_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Check_Exists_Throws_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Delete_Throws_An_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Delete_Throws_An_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Second_Call_Within_Polling_Interval()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Second_Call_Within_Polling_Interval()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Second_Call_Not_Within_Polling_Interval()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Second_Call_Not_Within_Polling_Interval()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentDeleteForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Delete_Throws_An_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.DeploymentCreateForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Check_Exists_Throws_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Check_Exists_Throws_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_Not_In_The_Scheduled_Time()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_But_Not_On_A_Scheduled_Day()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Does_Not_Exist()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Check_Exists_Throws_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_GetConfiguration_Throws_An_Error()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Second_Call_Within_Polling_Interval()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Second_Call_Not_Within_Polling_Interval()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.Forecast.Tests.WindowsAzure.HostedService.ScheduledHorizontalScaleForecastWorkerTests.#UnitTestDoWork_With_Now_In_The_Scheduled_Time_And_Deployment_Exists_And_Requires_Scaling_Out()")]
