//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// The StealFocusForecastConfiguration Configuration Section.
    /// </summary>
    public partial class StealFocusForecastConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the StealFocusForecastConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string StealFocusForecastConfigurationSectionName = "stealFocusForecastConfiguration";
        
        /// <summary>
        /// Gets the StealFocusForecastConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public static global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration Instance
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.StealFocusForecastConfigurationSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region WindowsAzureSubscriptions Property
        /// <summary>
        /// The XML name of the <see cref="WindowsAzureSubscriptions"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string WindowsAzureSubscriptionsPropertyName = "windowsAzureSubscriptions";
        
        /// <summary>
        /// Gets or sets the WindowsAzureSubscriptions.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The WindowsAzureSubscriptions.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzureSubscriptionsPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElementCollection WindowsAzureSubscriptions
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElementCollection)(base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzureSubscriptionsPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzureSubscriptionsPropertyName] = value;
            }
        }
        #endregion
        
        #region WindowsAzurePackages Property
        /// <summary>
        /// The XML name of the <see cref="WindowsAzurePackages"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string WindowsAzurePackagesPropertyName = "windowsAzurePackages";
        
        /// <summary>
        /// Gets or sets the WindowsAzurePackages.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The WindowsAzurePackages.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzurePackagesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElementCollection WindowsAzurePackages
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElementCollection)(base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzurePackagesPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzurePackagesPropertyName] = value;
            }
        }
        #endregion
        
        #region WindowsAzureDeploymentDeletes Property
        /// <summary>
        /// The XML name of the <see cref="WindowsAzureDeploymentDeletes"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string WindowsAzureDeploymentDeletesPropertyName = "windowsAzureDeploymentDeletes";
        
        /// <summary>
        /// Gets or sets the WindowsAzureDeploymentDeletes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The WindowsAzureDeploymentDeletes.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzureDeploymentDeletesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElementCollection WindowsAzureDeploymentDeletes
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElementCollection)(base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzureDeploymentDeletesPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.StealFocusForecastConfiguration.WindowsAzureDeploymentDeletesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// A collection of WindowsAzureSubscriptionConfigurationElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElementCollection.WindowsAzureSubscriptionConfigurationElementPropertyName)]
    public partial class WindowsAzureSubscriptionConfigurationElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string WindowsAzureSubscriptionConfigurationElementPropertyName = "windowsAzureSubscription";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElementCollection.WindowsAzureSubscriptionConfigurationElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElementCollection.WindowsAzureSubscriptionConfigurationElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement)(element)).Id;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement this[int index]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement this[object id]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement)(base.BaseGet(id)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="windowsAzureSubscription">The <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement windowsAzureSubscription)
        {
            base.BaseAdd(windowsAzureSubscription);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="windowsAzureSubscription">The <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement windowsAzureSubscription)
        {
            base.BaseRemove(this.GetElementKey(windowsAzureSubscription));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement GetItemAt(int index)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement GetItemByKey(string id)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement)(base.BaseGet(((object)(id)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// The WindowsAzureSubscriptionConfigurationElement Configuration Element.
    /// </summary>
    public partial class WindowsAzureSubscriptionConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region SubscriptionId Property
        /// <summary>
        /// The XML name of the <see cref="SubscriptionId"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string SubscriptionIdPropertyName = "subscriptionId";
        
        /// <summary>
        /// Gets or sets the SubscriptionId.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The SubscriptionId.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.SubscriptionIdPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string SubscriptionId
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.SubscriptionIdPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.SubscriptionIdPropertyName] = value;
            }
        }
        #endregion
        
        #region CertificateThumbprint Property
        /// <summary>
        /// The XML name of the <see cref="CertificateThumbprint"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string CertificateThumbprintPropertyName = "certificateThumbprint";
        
        /// <summary>
        /// Gets or sets the CertificateThumbprint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The CertificateThumbprint.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.CertificateThumbprintPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string CertificateThumbprint
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.CertificateThumbprintPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.CertificateThumbprintPropertyName] = value;
            }
        }
        #endregion
        
        #region Id Property
        /// <summary>
        /// The XML name of the <see cref="Id"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string IdPropertyName = "id";
        
        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Id.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.IdPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Id
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.IdPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureSubscriptionConfigurationElement.IdPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// A collection of WindowsAzurePackageConfigurationElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElementCollection.WindowsAzurePackageConfigurationElementPropertyName)]
    public partial class WindowsAzurePackageConfigurationElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string WindowsAzurePackageConfigurationElementPropertyName = "windowsAzurePackage";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElementCollection.WindowsAzurePackageConfigurationElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElementCollection.WindowsAzurePackageConfigurationElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement)(element)).Id;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement this[int index]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement this[object id]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement)(base.BaseGet(id)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="windowsAzurePackage">The <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement windowsAzurePackage)
        {
            base.BaseAdd(windowsAzurePackage);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="windowsAzurePackage">The <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement windowsAzurePackage)
        {
            base.BaseRemove(this.GetElementKey(windowsAzurePackage));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement GetItemAt(int index)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement GetItemByKey(string id)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement)(base.BaseGet(((object)(id)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// The WindowsAzurePackageConfigurationElement Configuration Element.
    /// </summary>
    public partial class WindowsAzurePackageConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region storageAccountName Property
        /// <summary>
        /// The XML name of the <see cref="storageAccountName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string storageAccountNamePropertyName = "storageAccountName";
        
        /// <summary>
        /// Gets or sets the storageAccountName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The storageAccountName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.storageAccountNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string storageAccountName
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.storageAccountNamePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.storageAccountNamePropertyName] = value;
            }
        }
        #endregion
        
        #region containerName Property
        /// <summary>
        /// The XML name of the <see cref="containerName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string containerNamePropertyName = "containerName";
        
        /// <summary>
        /// Gets or sets the containerName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The containerName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.containerNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string containerName
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.containerNamePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.containerNamePropertyName] = value;
            }
        }
        #endregion
        
        #region blobName Property
        /// <summary>
        /// The XML name of the <see cref="blobName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string blobNamePropertyName = "blobName";
        
        /// <summary>
        /// Gets or sets the blobName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The blobName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.blobNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string blobName
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.blobNamePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.blobNamePropertyName] = value;
            }
        }
        #endregion
        
        #region Id Property
        /// <summary>
        /// The XML name of the <see cref="Id"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string IdPropertyName = "id";
        
        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Id.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.IdPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Id
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.IdPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzurePackageConfigurationElement.IdPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// A collection of WindowsAzureDeploymentDeleteConfigurationElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElementCollection.WindowsAzureDeploymentDeleteConfigurationElementPropertyName)]
    public partial class WindowsAzureDeploymentDeleteConfigurationElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string WindowsAzureDeploymentDeleteConfigurationElementPropertyName = "windowsAzureDeploymentDelete";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElementCollection.WindowsAzureDeploymentDeleteConfigurationElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElementCollection.WindowsAzureDeploymentDeleteConfigurationElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement)(element)).Id;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement this[int index]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement this[object id]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement)(base.BaseGet(id)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="windowsAzureDeploymentDelete">The <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement windowsAzureDeploymentDelete)
        {
            base.BaseAdd(windowsAzureDeploymentDelete);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="windowsAzureDeploymentDelete">The <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement windowsAzureDeploymentDelete)
        {
            base.BaseRemove(this.GetElementKey(windowsAzureDeploymentDelete));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement GetItemAt(int index)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="id">The key of the <see cref="global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement GetItemByKey(string id)
        {
            return ((global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement)(base.BaseGet(((object)(id)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// The WindowsAzureDeploymentDeleteConfigurationElement Configuration Element.
    /// </summary>
    public partial class WindowsAzureDeploymentDeleteConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ServiceName Property
        /// <summary>
        /// The XML name of the <see cref="ServiceName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ServiceNamePropertyName = "serviceName";
        
        /// <summary>
        /// Gets or sets the ServiceName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ServiceName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.ServiceNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string ServiceName
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.ServiceNamePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.ServiceNamePropertyName] = value;
            }
        }
        #endregion
        
        #region DailyStartTime Property
        /// <summary>
        /// The XML name of the <see cref="DailyStartTime"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string DailyStartTimePropertyName = "dailyStartTime";
        
        /// <summary>
        /// Gets or sets the DailyStartTime.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The DailyStartTime.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DailyStartTimePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public global::System.TimeSpan DailyStartTime
        {
            get
            {
                return ((global::System.TimeSpan)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DailyStartTimePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DailyStartTimePropertyName] = value;
            }
        }
        #endregion
        
        #region Id Property
        /// <summary>
        /// The XML name of the <see cref="Id"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string IdPropertyName = "id";
        
        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Id.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.IdPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Id
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.IdPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.IdPropertyName] = value;
            }
        }
        #endregion
        
        #region SubscriptionConfigurationId Property
        /// <summary>
        /// The XML name of the <see cref="SubscriptionConfigurationId"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string SubscriptionConfigurationIdPropertyName = "subscriptionConfigurationId";
        
        /// <summary>
        /// Gets or sets the SubscriptionConfigurationId.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The SubscriptionConfigurationId.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.SubscriptionConfigurationIdPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public string SubscriptionConfigurationId
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.SubscriptionConfigurationIdPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.SubscriptionConfigurationIdPropertyName] = value;
            }
        }
        #endregion
        
        #region PollingIntervalInMinutes Property
        /// <summary>
        /// The XML name of the <see cref="PollingIntervalInMinutes"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string PollingIntervalInMinutesPropertyName = "pollingIntervalInMinutes";
        
        /// <summary>
        /// Gets or sets the PollingIntervalInMinutes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The PollingIntervalInMinutes.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.PollingIntervalInMinutesPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public int PollingIntervalInMinutes
        {
            get
            {
                return ((int)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.PollingIntervalInMinutesPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.PollingIntervalInMinutesPropertyName] = value;
            }
        }
        #endregion
        
        #region DailyEndTime Property
        /// <summary>
        /// The XML name of the <see cref="DailyEndTime"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string DailyEndTimePropertyName = "dailyEndTime";
        
        /// <summary>
        /// Gets or sets the DailyEndTime.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The DailyEndTime.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DailyEndTimePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public global::System.TimeSpan DailyEndTime
        {
            get
            {
                return ((global::System.TimeSpan)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DailyEndTimePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DailyEndTimePropertyName] = value;
            }
        }
        #endregion
        
        #region DeploymentSlots Property
        /// <summary>
        /// The XML name of the <see cref="DeploymentSlots"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string DeploymentSlotsPropertyName = "deploymentSlots";
        
        /// <summary>
        /// Gets or sets the DeploymentSlots.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The DeploymentSlots.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DeploymentSlotsPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElementCollection DeploymentSlots
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElementCollection)(base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DeploymentSlotsPropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.WindowsAzureDeploymentDeleteConfigurationElement.DeploymentSlotsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// A collection of DeploymentSlotConfigurationElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElementCollection.DeploymentSlotConfigurationElementPropertyName)]
    public partial class DeploymentSlotConfigurationElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string DeploymentSlotConfigurationElementPropertyName = "deploymentSlot";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override string ElementName
        {
            get
            {
                return global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElementCollection.DeploymentSlotConfigurationElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElementCollection.DeploymentSlotConfigurationElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement this[int index]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement this[object name]
        {
            get
            {
                return ((global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="deploymentSlot">The <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Add(global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement deploymentSlot)
        {
            base.BaseAdd(deploymentSlot);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="deploymentSlot">The <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public void Remove(global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement deploymentSlot)
        {
            base.BaseRemove(this.GetElementKey(deploymentSlot));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement GetItemAt(int index)
        {
            return ((global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement GetItemByKey(string name)
        {
            return ((global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace StealFocus.Forecast.Configuration
{
    
    
    /// <summary>
    /// The DeploymentSlotConfigurationElement Configuration Element.
    /// </summary>
    public partial class DeploymentSlotConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public string Name
        {
            get
            {
                return ((string)(base[global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement.NamePropertyName]));
            }
            set
            {
                base[global::StealFocus.Forecast.Configuration.DeploymentSlotConfigurationElement.NamePropertyName] = value;
            }
        }
        #endregion
    }
}
